/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule RelayRoot_Query.graphql
 * @generated SignedSource<<22584f1ef20da0de0749e7a8c2a89389>>
 * @relayHash 60cc15ded8f455330093a3aa08cd0434
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query RelayRoot_Query {
  store {
    ...ClientRouter_store
    id
  }
}

fragment ClientRouter_store on Store {
  anonymous
  ...Home_store
  ...User_store
  ...Header_store
}

fragment Home_store on Store {
  anonymous
  anonymousInfo {
    message
  }
}

fragment User_store on Store {
  anonymous
  anonymousInfo {
    message
  }
  ...LoginCard_store
  ...RegisterCard_store
}

fragment Header_store on Store {
  anonymous
  loginInfo {
    username
  }
}

fragment LoginCard_store on Store {
  anonymous
  anonymousInfo {
    message
  }
}

fragment RegisterCard_store on Store {
  anonymous
  anonymousInfo {
    message
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "RelayRoot_Query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Store",
        "name": "store",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "ClientRouter_store",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "RelayRoot_Query",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "RelayRoot_Query",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Store",
        "name": "store",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "anonymous",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "AnonymousInfo",
            "name": "anonymousInfo",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "message",
                "storageKey": null
              }
            ],
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "LoginInfo",
            "name": "loginInfo",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "username",
                "storageKey": null
              }
            ],
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query RelayRoot_Query {\n  store {\n    ...ClientRouter_store\n    id\n  }\n}\n\nfragment ClientRouter_store on Store {\n  anonymous\n  ...Home_store\n  ...User_store\n  ...Header_store\n}\n\nfragment Home_store on Store {\n  anonymous\n  anonymousInfo {\n    message\n  }\n}\n\nfragment User_store on Store {\n  anonymous\n  anonymousInfo {\n    message\n  }\n  ...LoginCard_store\n  ...RegisterCard_store\n}\n\nfragment Header_store on Store {\n  anonymous\n  loginInfo {\n    username\n  }\n}\n\nfragment LoginCard_store on Store {\n  anonymous\n  anonymousInfo {\n    message\n  }\n}\n\nfragment RegisterCard_store on Store {\n  anonymous\n  anonymousInfo {\n    message\n  }\n}\n"
};

module.exports = batch;
