/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule App_store.graphql
 * @generated SignedSource<<397e3afbfcb72d3005751f8a8de7cac8>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type App_store = {| |};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "App_store",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "Home_store",
      "args": null
    },
    {
      "kind": "FragmentSpread",
      "name": "Header_store",
      "args": null
    }
  ],
  "type": "Store"
};

module.exports = fragment;
